### ISSUE TITLE
Only looks for serializers related to viewsets

### ISSUE THREAD

**Issue by camjw** [remastr/drf-typescript-generator#6]
Hey, I want to use this tool for my product but I've stuck more with APIViews than ModelViewSets so by default this package misses a lot of my serializers. It also doesn't seem to give an easy way to write the types to a file, which I'd obviously like.

Would it be okay if I opened a PR addressing these issues?

**Comment by napmn** [comment]
Hi, I'm working on changing the logic for discovering serializers - rather than using routers we will find classes that inherit from `APIView` and use them. That will solve your issue.

As for the question regarding outputting to a file - isn't redirecting stdout to file sufficient?
`python manage.py generate_types my_app > mytypes.ts`

**Comment by camjw** [comment]
Sorry I wasn't clear at all, I'd like one file per type rather than one big file with all the types in. But I suppose maybe that's an uncommon use case. 

Either way if you're going to search for serializers related to APIViews then that essentially solves my issue so close this issue if you like?
